// log using cpsmay, replace
*by Jean Roth Mon Mar 19 12:53:41 EST 2001
*Please report errors to jroth@nber.org
*Change output file name/location as desired

*run by opening stata, set mem 50m, 
*use cpsmayYY, where YY is the year of interest, do labels 
*rename variables with, for example, rename x1 rectype
label variable x1 "Record type"
label variable x2 "Month in sample"
label variable x3 "Sample (A or C)"
label variable x4 "Random Cluster (first ID field)"
label variable x5 "Segment number (second ID field)"
label variable x6 "Serial number (third ID field)"
label variable x7 "State Codes - 1969-72, 77-84"
label variable x8 "Region"
label variable x9 "*State Codes - 1975 version"
label variable x10 "Regional office"
label variable x11 "*SMSA rankings"
label variable x12 "Interviewer check"
label variable x13 "Noninterview cluster"
label variable x14 "Line number of respondent"
label variable x15 "Type of interview"
label variable x16 "Date completed"
label variable x17 "Did X do any work  last week?"
label variable x18 "Interviewer check  (hours range)"
label variable x19 "Absent from job or on layoff?"
label variable x20 "Looking for work last 4 weeks?"
label variable x21 "Check (continuing/departing rot.)"
label variable x22 "Sample (A or C)"
label variable x23 "*Land usage (urban/rural, farm)"
label variable x24 "Type of living quarters"
label variable x25 "*SMSA status code (central city)"
label variable x26 "Household number"
label variable x27 "Major activity last week"
label variable x28 "Hours worked last week all jobs"
label variable x29 "Usually work 35+ hours this job"
label variable x30 "*Reason less than 35 hours worked"
label variable x31 "Why absent from work"
label variable x32 "Getting wages for time off"
label variable x33 "Usually work 35+ hours this job"
label variable x34 "What doing to find work  #1"
label variable x35 "What doing to find work  #2"
label variable x36 "What doing to find work  #3"
label variable x37 "What doing to find work  #4"
label variable x38 "What doing to find work  #5"
label variable x39 "What doing to find work  #6"
label variable x40 "What doing to find work  #7"
label variable x41 "Why started looking for work"
label variable x42 "Weeks unemployed"
label variable x43 "Looking for full or part-time"
label variable x44 "Reason couldn't take job? (Y/N)"
label variable x45 "(lists reason)"
label variable x46 "When last worked full-time"
label variable x47 "When last worked for pay"
label variable x48 "Why left that job?"
label variable x49 "Wants regular job now?"
label variable x50 "Why not looking for work #1"
label variable x51 "Reason not looking       #2"
label variable x52 "Reason not looking #3"
label variable x53 "Reason not looking #4"
label variable x54 "Reason not looking #5"
label variable x55 "Reason not looking #6"
label variable x56 "Reason not looking #7"
label variable x57 "Reason not looking #8"
label variable x58 "Reason not looking #9"
label variable x59 "Reason not looking #10"
label variable x60 "Reason not looking #11"
label variable x61 "Intends to look in next 12 months?"
label variable x62 "*Class of worker"
label variable x63 "*Industry"
label variable x64 "*Occupation"
label variable x65 "Line number"
label variable x66 "Relationship to head of household"
label variable x67 "Age"
label variable x68 "Marital status"
label variable x69 "Race"
label variable x70 "Sex"
label variable x71 "Veteran status"
label variable x72 "Highest grade attended"
label variable x73 "Grade completed?"
label variable x74 "Family number for subdivided hhld"
label variable x75 "Employment status recode"
label variable x76 "Principal person of hhld?"
label variable x77 "Document count"
label variable x78 "Month"
label variable x79 "Year (last digit)"
label variable x80 "Weight (2 implied  decimals)"
label variable x81 "Errors charged to   enumerator"
label variable x82 "Type of PSU (self  representing?)"
label variable x83 "Incidence of poverty in area"
label variable x84 "SMSA size"
label variable x85 "Ethnicity"
label variable x86 "Age recode"
label variable x87 "Residence recode (always missing)"
label variable x88 "Race recode"
label variable x89 "Area recode"
label variable x90 "Poverty area code"
label variable x91 "Part-time status recode"
label variable x92 "Race-sex recode"
label variable x93 "Agricultural wage and salary?"
label variable x94 "Civilian labor force status"
label variable x95 "Full/part-time status"
label variable x96 "Experienced labor force status"
label variable x97 "Household relationship recode"
label variable x98 "Employed class of worker"
label variable x99 "Major occupation group"
label variable x100 "Labor force by time worked"
label variable x101 "Duration of unemployment"
label variable x102 "In civilian labor force?"
label variable x103 "Unemployed?"
label variable x104 "Unemployed 15+ weeks?"
label variable x105 "Other NILF?"
label variable x106 "Full time labor force?"
label variable x107 "Looking for full-time work?"
label variable x108 "Wage and salary worker?"
label variable x109 "Employed person?"
label variable x110 "Employed(nonfarm, non-hhld work)?"
label variable x111 "Experienced labor force?"
label variable x112 "Full-time experienced labor force?"
label variable x113 "Full-time or economic-part-time?"
label variable x114 "Nonfarm industry?"
label variable x115 "Nonfarm wage and salary?"
label variable x116 "Agriculture?"
label variable x117 "White collar?"
label variable x118 "Blue collar?"
label variable x119 "Manufacturing, wage and salary?"
label variable x120 "Private wage and salary?"
label variable x121 "Part-time for noneconomic reasons?"
label variable x122 "Seeking full time work?"
label variable x123 "Unemployed-no previous experience?"
label variable x124 "Full-time labor force recode"
label variable x125 "Program signal"
label variable x126 "Program signal"
label variable x127 "Age-school recode"
label variable x128 "Age recode"
label variable x129 "Age-major activity recode"
label variable x130 "Age recode"
label variable x131 "Employed status-farm recode"
label variable x132 "Marital status-age recode"
label variable x133 "Marital status-activity recode"
label variable x134 "*Major industry"
label variable x135 "Detailed class of worker"
label variable x136 "Class-employed recode"
label variable x137 "*Major industry"
label variable x138 "*Detailed industry"
label variable x139 "*Major occupation"
label variable x140 "*Detailed occupation"
label variable x141 "*Manufacturing industries"
label variable x142 "Reason not working-hours recode"
label variable x143 "Reason part time-hours recode"
label variable x144 "Detailed reason-hours recode"
label variable x145 "Covered by collective agreement"
label variable x146 "Reason-pay status recode"
label variable x147 "Program signal  so"
label variable x148 "Gross Change employment-industry"
label variable x149 "G.C. expanded employment status"
label variable x150 "G.C. intermed. emp. status"
label variable x151 "G.C. industry"
label variable x152 "G.C. employment-occupation"
label variable x153 "G.C. age"
label variable x154 "G.C. summary age"
label variable x155 "G.C. duration of unemployment"
label variable x156 "G.C. summary duration of unemp."
label variable x157 "G.C. duration by full-p`1e`	qASZart time"
label variable x158 "G.C. employment and NILF"
label variable x159 "G.C. age-employment"
label variable x160 "G.C. age-employment (restricted)"
label variable x161 "G.C. education-employment"
label variable x162 "G.C. class-farm"
label variable x163 "G.C. industry"
label variable x164 "G.C. hours-at work"
label variable x165 "G.C. full/part reason"
label variable x166 "G.C. looking full/part - age"
label variable x167 "Number under 18, related to head"
label variable x168 "Total family income"
label variable x169 "Usual weekly earnings"
label variable x170 "Work for 2+ employers?"
label variable x171 "Operate own business?"
label variable x172 "Have other job (not worked)?"
label variable x173 "Check (40 or more hours)"
label variable x174 "Get higher pay for over 40 hours?"
label variable x175 "Usually work over 40 hours?"
label variable x176 "Did X also work regular job?"
label variable x177 "Another job, not worked?"
label variable x178 "Another job, not worked? (recode)"
label variable x179 "Was second job same?"
label variable x180 "Reason worked second job"
label variable x181 "Hours worked second job"
label variable x182 "Hours worked principal job"
label variable x183 "Check/recode"
label variable x184 "Days per week usually works (code)"
label variable x185 "Hours per week usually works"
label variable x186 "Usually weekly earnings"
label variable x187 "Paid by the hour?"
label variable x188 "Earnings per hour (cents)"
label variable x189 "Belong to labor union?"
label variable x190 "Who reported income data?"
label variable x191 "Second industry recode"
label variable x192 "Second occupation recode"
label variable x193 "Secondary class of worker"
label variable x194 "Dual job/unpaid job recode"
label variable x195 "Time of day begins work"
label variable x196 "AM/PM begins"
label variable x197 "Time of day ends work"
label variable x198 "AM/PM ends"
label variable x199 "Rotation group 3/other?"
label variable x200 "Year"
